version: '3.9'
services:
  api:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}api:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: ./build/development.Dockerfile
    volumes:
      - ./:/go/src/gitlab.void-ptr.org/go/schism:rw
    ports:
      - 8080:8080