version: '3.9'
services:
  api:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}api:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    networks:
      - schism
    environment:
      - BUILD_ENV
    secrets:
      - source: schism.api.secret
        uid: '999'
        mode: 0400
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.docker.network=schism_frontend"
      - "traefik.frontend.rule=schism.${DOMAIN}"
      - "traefik.port=80"
  db:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}sqlite:${DOCKER_TAG}
    build:
      context: ./sqlite
      dockerfile: ./Dockerfile
    networks:
      - schism

networks:
  schism:

secrets:
  schism.api.secret:
    file: .secrets/schism.api.secret