version: '3.9'
services:
  schism:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}schism:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: ./build/development.Dockerfile
    volumes:
      - ./:/go/src/gitlab.void-ptr.org/go/schism:rw,delegated
      - ./schism.sqlite:/db/schism.sqlite:rw,delegated
    ports:
      - 8080:8080
      - 2345:2345

  influxdb:
    ports:
      - 8086:8086

  grafana:
    ports:
      - 3000:3000
