version: '3.9'
services:
  api:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}api:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    networks:
      - schism
    environment:
      - BUILD_ENV=${BUILD_ENV}
      - GIT_COMMIT=${GIT_COMMIT}
      - GIT_TAG=${GIT_TAG}
    secrets:
      - source: schism.api.secret
        uid: '999'
        mode: 400
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=schism_frontend"
        - "traefik.frontend.rule=schism.${DOMAIN}"
        - "traefik.port=80"
    volumes:
      - sqlite:/db:rw

  influxdb:
    image: influxdb:2.1
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
    volumes:
      - ./influxdb/config.yml:/etc/influxdb/influxdb.conf:ro
      - data:/var/lib/influxdb:rw

volumes:
  sqlite:
  data:

    null
networks:
  schism:

    null
secrets:
  schism.api.secret:
    file: .secrets/schism.api.secret
