version: '3.9'
services:
  schism:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}schism:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    depends_on:
      - influxdb
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=${API_DOMAIN:-api.schism.void-ptr.org}
      - VIRTUAL_PORT=8080
      - SELF_SIGNED_HOST=${schism.void-ptr.org}

  influxdb:
    restart: unless-stopped

  grafana:
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=${GRAFANA_DOMAIN:-grafana.schism.void-ptr.org}
      - VIRTUAL_PORT=3000
      - SELF_SIGNED_HOST=${schism.void-ptr.org}

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro

  proxy-companion:
    restart: always
    image: sebastienheyd/self-signed-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs

networks:
  nginx-proxy:
