version: '3.9'
services:
  api:
    image: ${DOCKER_REGISTRY}${IMAGE_PREFIX}api:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: ./build/development.Dockerfile
    volumes:
      - ./:/go/src/gitlab.void-ptr.org/go/schism:rw,delegated
    ports:
      - 8080
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=${API_DOMAIN:-dev.void-ptr.org}
      - SELF_SIGNED_HOST=${API_DOMAIN:-dev.void-ptr.org}
      - LETSENCRYPT_HOST=${API_DOMAIN:-dev.void-ptr.org}
      - LETSENCRYPT_EMAIL=admin@void-ptr.org

  influxdb:

  grafana:
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${GRAFANA_DOMAIN:-grafana.dev.void-ptr.org}
      - SELF_SIGNED_HOST=${GRAFANA_DOMAIN:-grafana.dev.void-ptr.dev}
      - LETSENCRYPT_HOST=${API_DOMAIN:-grafana.dev.void-ptr.org}
      - LETSENCRYPT_EMAIL=admin@void-ptr.org

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-proxy
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy


networks:
  nginx-proxy: