apiVersion: 1

deleteDatasources:
  - name: schism
    orgId: 1

datasources:
  - name: schism
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: 3c0861324c9719713f4d9caeb5887494905a7d42
    jsonData:
      version: Flux
      organization: schism
      defaultBucket: sensors
      tlsSkipVerify: true
